//! Error details

use core::result::Result as CoreResult;
use thiserror::Error as ThisError;

/// An enumeration of errors which this library may generate.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, ThisError)]
pub enum Error {
    /// There are not enough or too many bytes for a CFI code.
    #[error("Invalid length")]
    InvalidLength,

    /// The category character is invalid.
    #[error("Invalid category '{0}'")]
    InvalidCategory(char),

    /// The group character is invalid.
    #[error("Invalid group '{0}'")]
    InvalidGroup(char),

    /// The voting right character is invalid.
    #[error("Invalid voting right '{0}'")]
    InvalidVotingRight(char),

    /// The ownership character is invalid.
    #[error("Invalid ownership restriction '{0}'")]
    InvalidOwnership(char),

    /// The payment status character is invalid.
    #[error("Invalid payment status '{0}'")]
    InvalidPaymentStatus(char),

    /// The redemption character is invalid.
    #[error("Invalid redemption '{0}'")]
    InvalidRedemption(char),

    /// The given byte is not a valid form character.
    #[error("Invalid form '{0}'")]
    InvalidForm(char),

    /// The given byte is not a valid unassigned attribute character.
    #[error("Invalid unassigned '{0}'")]
    InvalidUnassigned(char),

    /// The given byte is not a valid income character.
    #[error("Invalid income '{0}'")]
    InvalidIncome(char),

    /// The given byte is not a valid dependency character.
    #[error("Invalid dependency '{0}'")]
    InvalidDependency(char),

    /// The given byte is not a valid redemption/conversion character.
    #[error("Invalid redemption/conversion '{0}'")]
    InvalidRedemptionConversion(char),

    /// The given byte is not a valid structured type character.
    #[error("Invalid structured type '{0}'")]
    InvalidStructuredKind(char),

    /// The given byte is not a valid distribution character.
    #[error("Invalid distribution '{0}'")]
    InvalidDistribution(char),

    /// The given byte is not a valid repayment character.
    #[error("Invalid repayment '{0}'")]
    InvalidRepayment(char),

    /// The given byte is not a valid asset character.
    #[error("Invalid underlying asset '{0}'")]
    InvalidAsset(char),

    /// The given byte is not a valid interest, in-kind, or cash character.
    #[error("Invalid interest, in-kind, or cash '{0}'")]
    InvalidInterestInKindOrCash(char),

    /// The given byte is not a valid guarantee character.
    #[error("Invalid guarantee '{0}'")]
    InvalidGuarantee(char),

    /// The given byte is not a valid interest or in-kind character.
    #[error("Invalid interest or in-kind '{0}'")]
    InvalidInterestInKind(char),

    /// The given byte is not a valid type of structured debt instrument with protection.
    #[error("Invalid protected structured debt type '{0}'")]
    InvalidProtectedKind(char),

    /// The given byte is not a valid type of structured debt instrument without protection.
    #[error("Invalid unprotected structured debt type '{0}'")]
    InvalidUnprotectedKind(char),

    /// The given byte is not a valid interest or cash character.
    #[error("Invalid interest or cash '{0}'")]
    InvalidInterestOrCash(char),

    /// The given byte is not a valid interest character.
    #[error("Invalid interest '{0}'")]
    InvalidInterest(char),

    /// The given byte is not a valid type of other instrument character.
    #[error("Invalid other kind '{0}'")]
    InvalidOtherKind(char),

    /// The given byte is not a valid closed/open-ended character.
    #[error("Invalid closed/open-ended '{0}'")]
    InvalidClosedOrOpen(char),

    /// The given byte is not a valid security type/investor restriction character.
    #[error("Invalid security type and investor restriction '{0}'")]
    InvalidKindAndRestriction(char),

    /// The given byte is not a valid strategy character.
    #[error("Invalid strategy '{0}'")]
    InvalidStrategy(char),

    /// The given byte is not a valid security type character.
    #[error("Invalid security type '{0}'")]
    InvalidKind(char),

    /// The given byte is not a valid style character.
    #[error("Invalid style '{0}'")]
    InvalidStyle(char),

    /// The given byte is not a valid call/put character.
    #[error("Invalid call/put '{0}'")]
    InvalidCallPut(char),

    /// The given byte is not a valid exercise option style character.
    #[error("Invalid exercise option style '{0}'")]
    InvalidExerciseStyle(char),

    /// The given byte is not a valid barrier dependency character.
    #[error("Invalid barrier dependency type '{0}'")]
    InvalidBarrier(char),

    /// The given byte is not a valid long/short character.
    #[error("Invalid long/short '{0}'")]
    InvalidLongShort(char),
}

/// A convenience wrapper for results generated by this library.
pub type Result<T, E = Error> = CoreResult<T, E>;
