//! Error details

use core::result::Result as CoreResult;
use thiserror::Error as ThisError;

/// An enumeration of errors which this library may generate.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, ThisError)]
pub enum Error {
    /// The given byte is invalid for it's context.
    #[error("Invalid byte: '{0}'")]
    InvalidByte(u8),
}

/// A convenience wrapper for results generated by this library.
pub type Result<T, E = Error> = CoreResult<T, E>;
